### PR TITLE
Support azuread style "federated" authentication

### LINKED ISSUE #30: Login as AAD User
Hello!

My organization uses free Azure AD, so we don't want to but the P1 level. Problem is that when using free Azure AD users from an external provider can be added only via AD User. It's not possible via Service Principal (P1 level needed and role Directory Readers) or via SQL Account (Only from AAD users it can be). So currently there is a need to manually login into Azure SQL Database and add a user via SQL command (CREATE USER .. FROM EXTERNAL PROVIDER). So we want to automatize that, but the only way to do that is to log in as an AD User. In the current implementation of the provider, I haven't seen such an option to do that. Maybe I'm missing some option?

### PR DESCRIPTION
**Pull request by bittrance**
Fixes #30.

This PR implements two of the auth forms available through the new [fedauth](https://github.com/denisenkom/go-mssqldb#azure-active-directory-authentication): `ActiveDirectoryDefault` and `ActiveDirectoryManagedIdentity` (because user-assigned identity) as these are the most useful variants.

### CODE REVIEW

**Comment by jnsvd** [comment]
Also very interested in this feature, thanks a lot for providing it.

**Comment by Ivan-L** [comment]
Also very interested in this PR going in. I see that there is documentation and a series of tests. Tagging @magne :)

**Comment by waltervos** [comment]
@bittrance Is the `azuread_default_chain_auth` meant to work with these environment variables? https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet

**Comment by bittrance** [comment]
@waltervos  I don't have an easy way of testing, but according to https://github.com/denisenkom/go-mssqldb#azure-active-directory-authentication it should start with trying "EnvironmentCredential" so I would expect so. (Indeed, a colleague warned me that there are situations where you may get envs injected that you want to ignore and this is why I implemented the MSI-specific variant.)

**Review by magne — APPROVED** [review]

**Pull request merged**
